version: "2"

services:
  app:
    container_name: app
    restart: always
    build: service
    depends_on:
      - mongo
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo